import { useGetDonations } from "@/api/useGetDonations";
import CoffeeDonateCard from "@/components/CoffeeDonateCard/CoffeeDonateCard";
import ErrorCoffee from "@/components/ErrorCoffee/ErrorCoffee";
import LoadingCoffee from "@/components/LoadingCoffee/LoadingCoffee";
import MyInfoCard from "@/components/MyInfoCard/MyInfoCard";
import Timeline from "@/components/Timeline/Timeline";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const donations = useGetDonations();

  if (donations.isLoading) return <LoadingCoffee />;
  if (donations.isError || !donations.data) return <ErrorCoffee />;

  return (
    <>
      <Head>
        <title>Buy Forest a coffee...or five </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyInfoCard />

      <div className="flex w-full flex-row-reverse flex-wrap-reverse items-start justify-center space-x-2 sm:flex-row sm:flex-nowrap">
        <Timeline records={donations.data.records} />
        <CoffeeDonateCard />
      </div>
    </>
  );
};

export default Home;
